fix: exports types
single-spa/single-spa-react pull request #183
Opened 2023-07-30 19:38 UTC by stefan-karlsson

Makes sure that the correct Typescript definitions are exported when exports property in package.json is used.

2023-10-04 21:11 UTC, MilanKovacic requested changes
Hi, thank you for submitting the PR. There are still some problems left to fix. Let me know if you need any help. See the following image:

![image](https://github.com/single-spa/single-spa-react/assets/9189985/400e2c0b-77c4-4ccb-98e3-23193e0d8850)

Testing done with https://arethetypeswrong.github.io/.
Essentially, exports need to be reformatted (split) as follows:

```json
{
  "exports": {
    ".": {
      "import": {
        "types": "./index.d.ts",
        "default": "./index.js"
      },
      "require": {
        "types": "./index.d.cts",
        "default": "./index.cjs"
      }
    }
  }
}
```
There also has to be an additional types declaration file (see index.d.cts in the example) for the CJS format.
After reviewing the code, there is a mix of default and named exports which can (rarely) cause problems when package is consumed in CJS format (see https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/CJSOnlyExportsDefault.md). Rollup does not correctly handle this case, so the solution is to either patch the code to add the interopability, patch the output, or remove the default export (which is of course, a breaking change). This one can wait 😄

2023-10-13 08:10 UTC, MilanKovacic commented
@stefan-karlsson If you do not have time to make the proposed changes, let me know and I will do them.

2023-10-13 09:26 UTC, stefan-karlsson commented
> @stefan-karlsson If you do not have time to make the proposed changes, let me know and I will do them.

You are free to help out if you want. Have quite a lot at my work atm :)

2023-10-13 19:42 UTC, stefan-karlsson commented
Close in favor of #196

2023-10-13 19:42 UTC, closed without merging